version: '3.7'

services:

  database:
    image: oracle/database:18.4.0-xe
    container_name: oracle
    environment:
      - TZ=Europe/Oslo
      - ORACLE_PWD=oracle
    volumes:
      - oradata:/opt/oracle/oradata
    ports:
      - 1521:1521
    networks:
      - dbnet
    init: true
    healthcheck:
      test: sql -L -S sys/oracle@localhost:1521/XEPDB1 as sysdba < /dev/null |grep 'ORA-'; if [[ $$? == 1 ]]; then echo 0; else echo 1; fi
      interval: 1m
      timeout: 10s
      retries: 20
      start_period: 40s

  app:
    env_file: .env
    image: oracle/restdataservices:18.4.0
    container_name: app
    environment:
      - TZ=Europe/Oslo
      - ORACLE_HOST=database
      - ORACLE_PORT=1521
      - ORACLE_SERVICE=XEPDB1
      - ORACLE_PWD=oracle
      - ORDS_PWD=oracle
    init: true
    volumes:
      - ords-config:/opt/oracle/ords/config/ords
      - apex-images:/opt/oracle/ords/doc_root/i
    ports:
      - 8888:8888
    networks:
      - dbnet
    init: true
    restart: on-failure
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/ords"]
      interval: 30s
      timeout: 10s
      retries: 100
      start_period: 40s

networks:
  dbnet:

volumes:
   oradata:
     driver: local
     driver_opts:
       device: $PWD/oradata
       o: bind
   apex-images:
     driver: local
     driver_opts:
       device: $PWD/apex/${APEX_VERSION}/apex/images
       o: bind
   ords-config:
     driver: local
     driver_opts:
       device: $PWD/ords/ords-${ORDS_VERSION}/config
       o: bind
