version: '2.2'

services:

  database:
    image: oracle/database:18.4.0-xe
    container_name: oracle
    environment:
      - TZ=Europe/Oslo
      - ORACLE_PWD=oracle
    volumes:
      - oradata:/opt/oracle/oradata
    ports:
      - 1521:1521
    networks:
      - dbnet
    init: true
    healthcheck:
      test: sql -L -S sys/oracle@localhost:1521/XE as sysdba < /dev/null |grep 'ORA-'; if [[ $$? == 1 ]]; then echo 0; else echo 1; fi
      interval: 2m
      timeout: 30s
      retries: 20

  create-ords-config:
    env_file: .env
    image: ords:${ORDS_VERSION}
    container_name: create-ords-config
    environment:
      - TZ=Europe/Oslo
      - DB_HOSTNAME=database
      - DB_PORT=1521
      - DB_SERVICENAME=XEPDB1
      - APEX_PUBLIC_USER_PASS=oracle
      - APEX_LISTENER_PASS=oracle
      - APEX_REST_PASS=oracle
      - ORDS_PASS=oracle
      - SYS_PASS=oracle
    init: true
    volumes:
      - ords-config:/opt/ords
    networks:
      - dbnet

  app:
    env_file: .env
    image: ords:${ORDS_VERSION}
    container_name: ords
    environment:
      - TZ=Europe/Oslo
      - DB_HOSTNAME=database
      - DB_PORT=1521
      - DB_SERVICENAME=XEPDB1
      - APEX_PUBLIC_USER_PASS=oracle
      - APEX_LISTENER_PASS=oracle
      - APEX_REST_PASS=oracle
      - ORDS_PASS=oracle
      - SYS_PASS=oracle
    volumes:
      - ords-config:/opt/ords
      - apex-images:/ords/apex-images
    ports:
      - 8080:8080
    networks:
      - dbnet
    init: true
    restart: on-failure
  wait_until_ready:
    image: oracle/database:18.4.0-xe
    command: /usr/bin/true
    depends_on: {"database": {"condition": "service_healthy"}}

networks:
  dbnet:

volumes:
   oradata:
     driver: local
     driver_opts:
       device: $PWD/oradata
       o: bind
   apex-images:
     driver: local
     driver_opts:
       device: $PWD/apex/${APEX_VERSION}/apex/images
       o: bind
   ords-config:
     driver: local
     driver_opts:
       device: $PWD/ords/ords-${ORDS_VERSION}/config
       o: bind
